# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDownloadDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_download_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductImagesDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_images_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('detail', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('order_index', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
        migrations.CreateModel(
            name='ProductMovieDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_alias', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('release_time', models.DateField(blank=True, default=datetime.date(2017, 3, 29), null=True)),
                ('about', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'product_movie_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductSubTypeDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductInfo')),
            ],
            options={
                'db_table': 'product_sub_type_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(default=0)),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=200, null=True)),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='PublicDataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('source_type', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'public_data_source',
            },
        ),
        migrations.CreateModel(
            name='PublicDownloadAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('download_url', models.CharField(max_length=1000)),
                ('download_type', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'public_download_address',
            },
        ),
        migrations.CreateModel(
            name='PublicImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('img_type', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'public_images',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('word_type', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'sensitive_words',
            },
        ),
        migrations.AddField(
            model_name='productsubtypedetail',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductType'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductType'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.PublicDataSource'),
        ),
        migrations.AddField(
            model_name='productimagesdetail',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.PublicImages'),
        ),
        migrations.AddField(
            model_name='productimagesdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductInfo'),
        ),
        migrations.AddField(
            model_name='productdownloaddetail',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.PublicDownloadAddress'),
        ),
        migrations.AddField(
            model_name='productdownloaddetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductInfo'),
        ),
    ]
