# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('tag', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'sensitive_words',
            },
        ),
    ]
