# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_comment_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductCommentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_name', models.CharField(max_length=50)),
                ('comment_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_comment_info',
            },
        ),
        migrations.AlterField(
            model_name='productmoviedetail',
            name='release_time',
            field=models.DateField(blank=True, default=datetime.date(2017, 3, 30), null=True),
        ),
        migrations.AddField(
            model_name='productcommentdetail',
            name='comment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductCommentInfo'),
        ),
        migrations.AddField(
            model_name='productcommentdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ProductInfo'),
        ),
    ]
