# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170330_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentinfo',
            name='comment_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productmoviedetail',
            name='product_alias',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productmoviedetail',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
