# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170330_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('submit_time', models.DateField()),
            ],
            options={
                'db_table': 'submit_history',
            },
        ),
        migrations.AlterField(
            model_name='productmoviedetail',
            name='release_time',
            field=models.DateField(blank=True, default=datetime.date(2017, 4, 1), null=True),
        ),
    ]
