# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170401_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('desc', models.TextField(null=True)),
            ],
            options={
                'db_table': 'public_dictionary',
            },
        ),
    ]
