# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170314_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie_type',
            },
        ),
        migrations.CreateModel(
            name='MovieTypeDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_type_detail',
            },
        ),
        migrations.AddField(
            model_name='movieimages',
            name='img_type',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='release_time',
            field=models.DateField(blank=True, default=datetime.date(2017, 3, 18), null=True),
        ),
        migrations.AddField(
            model_name='movietypedetail',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieDetail'),
        ),
        migrations.AddField(
            model_name='movietypedetail',
            name='movie_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieType'),
        ),
    ]
