# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20170318_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='create_time',
            field=models.TimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='release_time',
            field=models.DateField(blank=True, default=datetime.date(2017, 3, 20), null=True),
        ),
    ]
