# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20170320_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
